name: CI/CD actions [Linux]
on:
  push:
    branches: [master, develop]
    tags:
      - 'v*'
  pull_request:
    branches: [master, develop]

jobs:
  cpplint:
    runs-on: ubuntu-latest
    name: Check GStyle with cpplint
    steps:
      - uses: actions/checkout@v2

      - name: Install cpplint
        run: pip3 install cpplint

      - name: Run cpplint
        run: find {benchmarks,tests,sources,wavelet_buffer,examples}/ -name "*.cc" -o -name "*.h" | xargs cpplint

  build_test:
    runs-on: ubuntu-latest
    name: Build and test C++ part
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          pip3 install conan
          sudo apt-get install lcov

      - name: Build tests, benchmarks and examples
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DWB_BUILD_TESTS=ON -DWB_BUILD_BENCHMARKS=ON -DWB_BUILD_EXAMPLES=ON -DCODE_COVERAGE=ON ..
          cmake --build . -j

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure

      - name: Install wavelet_buffer
        run: |
          cd build
          sudo cmake --install .

      - name: Check cmake target installation
        run: cmake --find-package -DNAME=wavelet_buffer -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST

      - name: Create code coverage report
        if: matrix.build_type == 'debug'
        run: |
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/build/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload code coverage report to codecov.io
        if: matrix.build_type == 'debug'
        uses: codecov/codecov-action@v2
        with:
          directory: .
          fail_ci_if_error: true
          files: ./coverage.info
          flags: unittests
          verbose: true

  conan:
    needs: [ build_test ]
    name: "Build Conan package and upload it"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install conan
        run: pip3 install conan

      - name: Prefix version for development version
        if: ${{ (github.ref == 'refs/heads/develop') }}
        run: echo "VERSION_SUFFIX=$(echo ${GITHUB_RUN_ID})" >> $GITHUB_ENV

      - name: Create profile
        run: |
          cd conan
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Build package for stable channel
        if: github.ref_type == 'tag'
        run: |
          cd conan
          CONAN_SOURCE_DIR=`pwd`/.. conan create . drift/stable

      - name: Build package for develop channel
        if: github.ref_type == 'branch'
        run: |
          cd conan
          CONAN_SOURCE_DIR=`pwd`/.. conan create . drift/develop

      - name: Upload package
        if: ${{ (github.ref == 'refs/heads/develop') || (startsWith(github.event.ref, 'refs/tags/v')) }}
        run: |
          conan remote add panda https://conan.panda.technology/artifactory/api/conan/drift
          conan user -p ${{secrets.CONAN_PASSWORD}} -r panda --skip-auth ${{secrets.CONAN_LOGIN_USERNAME}}
          conan upload wavelet_buffer --all --confirm --remote=panda

  pip:
    name: "Build and test PIP"
    #needs: [ conan ]
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ ubuntu-latest ]
        python-version: [ "3.8", "3.9", "3.10" ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build and install
        run: |
          pip install --verbose .[test]

      - name: Test
        run: |
          pytest python/tests

  build_sdist:
    name: "Build and test SDist"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prefix version for development version
        if: ${{ (github.ref == 'refs/heads/develop') }}
        run: echo "VERSION_SUFFIX=$(echo ${GITHUB_RUN_ID})" >> $GITHUB_ENV

      - name: Build SDist
        run: |
          pipx run build --sdist

      - name: Check metadata
        run: |
          pipx run twine check dist/*

      - name: Install SDist package
        run:  pip3 install dist/*

      - uses: actions/upload-artifact@v2
        with:
          path: dist/*.tar.gz

  build_wheels:
    name: "Build wheels on ${{ matrix.os }}"
    #needs: [pip]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.6.1

      - name: Prefix version for development version
        if: ${{ (github.ref == 'refs/heads/develop') }}
        run: echo "VERSION_SUFFIX=$(echo ${GITHUB_RUN_ID})" >> $GITHUB_ENV

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse .

      - name: Verify clean directory
        run: |
          git diff --exit-code
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

  upload_all:
    name: "Upload packages if release"
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    #if: github.event_name == 'release' && github.event.action == 'published'
    if: ${{ (github.ref == 'refs/heads/develop') || (startsWith(github.event.ref, 'refs/tags/v')) }}

    steps:
      - uses: actions/setup-python@v2

      - uses: actions/download-artifact@v2
        with:
          name: artifact
          path: dist

      - name: "Upload to panda PyPI"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://pypi.panda.technology

      - name: "Upload to PyPI"
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
