name: Run cpplint
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/cpplint.yml'
      - 'benchmarks/**'
      - 'examples'
      - 'sources/**'
      - 'tests/**'
      - 'wavelet_buffer/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/cpplint.yml'
      - 'benchmarks/**'
      - 'examples'
      - 'sources/**'
      - 'tests/**'
      - 'wavelet_buffer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cpplint
        run: find {benchmarks,tests,sources,wavelet_buffer,examples}/ -name "*.cc" -o -name "*.h" | xargs cpplint -file=Google

