name: Compile project and run C++ tests [Linux]
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-linux.yml'
      - 'CMakeLists.txt'
      - 'benchmarks/**'
      - 'sources/**'
      - 'tests/**'
      - 'wavelet_buffer/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test-linux.yml'
      - 'CMakeLists.txt'
      - 'benchmarks/**'
      - 'sources/**'
      - 'tests/**'
      - 'wavelet_buffer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [ Debug, Release ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependences
        run: |
          sudo apt-get install libopenblas-dev
          sudo apt-get install libjpeg-dev
          sudo apt-get install nlohmann-json3-dev
          git clone https://bitbucket.org/blaze-lib/blaze.git --depth=1 --branch=v3.8 && cd blaze && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ . && sudo make install
          git clone https://github.com/USCiLab/cereal --depth=1 --branch=v1.3.0 && cd cereal && cmake -DCMAKE_INSTALL_PREFIX=/usr/local/ -DJUST_INSTALL_CEREAL=ON . && sudo make install
      - name: Build tests, benchmarks and examples
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DWB_BUILD_TESTS=ON -DWB_BUILD_BENCHMARKS=ON -DWB_BUILD_EXAMPLES=ON ..
          cmake --build .
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
      - name: Install wavelet_buffer
        run: |
          cd build
          sudo cmake --install .
        
